
sudo: false

language: generic

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - fakeroot
    - git
    - libsecret-1-dev

env:
  global:
    - APM_TEST_PACKAGES="atom-mocha-test-runner"
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

os:
  - linux
  - osx

dist: trusty

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

branches:
  only:
    - master

git:
  depth: 10
